sudo: required
services: 
  - docker

before_install:
  - docker build  -t pghukasyan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pghukasyan/docker-react npm run test -- --coverage 

